### ISSUE TITLE
When I run it I get an error message

### ISSUE THREAD

**Issue by cabalamat** [jalanb/co.py.cat#13]
Stack trace:

```
$ python main.py abc abd ijk
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    sys.exit(main(sys.argv[0], sys.argv[1:]))
  File "main.py", line 21, in main
    answers = copycat.run(initial, modified, target, iterations)
  File "/home/phil/sproj/co.py.cat/copycat/copycat.py", line 60, in run
    runTrial(answers)
  File "/home/phil/sproj/co.py.cat/copycat/copycat.py", line 40, in runTrial
    lastUpdate = mainLoop(lastUpdate)
  File "/home/phil/sproj/co.py.cat/copycat/copycat.py", line 29, in mainLoop
    coderack.chooseAndRunCodelet()
  File "/home/phil/sproj/co.py.cat/copycat/coderack.py", line 281, in chooseAndRunCodelet
    self.run(codelet)
  File "/home/phil/sproj/co.py.cat/copycat/coderack.py", line 338, in run
    method(codelet)
  File "/home/phil/sproj/co.py.cat/copycat/codeletMethods.py", line 802, in bottom_up_correspondence_scout
    distinguishingMappings = [m for m in conceptMappings if m.distinguishing()]
  File "/home/phil/sproj/co.py.cat/copycat/conceptMapping.py", line 59, in distinguishing
    self.initialDescriptor):
  File "/home/phil/sproj/co.py.cat/copycat/letter.py", line 44, in distinguishingDescriptor
    if not WorkspaceObject.distinguishingDescriptor(self, descriptor):
TypeError: distinguishingDescriptor() takes exactly 1 argument (2 given)
```

**Comment by cabalamat** [comment]
it works now, thanks.
