### ISSUE TITLE
Trouble compiling

### ISSUE THREAD

**Issue by holdenlee** [jalanb/co.py.cat#5]
I'm having trouble compiling this under either Python 2.7 or 3.4. What is the intended python setup?

Here are the error messages:

$ C:/Python34/python main.py abc abd ijk
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    import copycat
  File "C:\Users\Owner\Dropbox\CS\AI\FARG\co.py.cat\copycat\copycat.py", line 49
    print "%d: %s" % (coderack.codeletsRun, answer)
                 ^
SyntaxError: invalid syntax

$ C:/Python27/python main.py abc abd ijk
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    sys.exit(main(sys.argv[0], sys.argv[1:]))
  File "main.py", line 13, in main
    copycat.run(initial, modified, target)
  File "C:\Users\Owner\Dropbox\CS\AI\FARG\co.py.cat\copycat\copycat.py", line 58, in run
    runTrial()
  File "C:\Users\Owner\Dropbox\CS\AI\FARG\co.py.cat\copycat\copycat.py", line 44, in runTrial
    lastUpdate = mainLoop(lastUpdate)
  File "C:\Users\Owner\Dropbox\CS\AI\FARG\co.py.cat\copycat\copycat.py", line 32, in mainLoop
    coderack.chooseAndRunCodelet()
  File "C:\Users\Owner\Dropbox\CS\AI\FARG\co.py.cat\copycat\coderack.py", line 285, in chooseAndRunCodelet
    self.run(codelet)
  File "C:\Users\Owner\Dropbox\CS\AI\FARG\co.py.cat\copycat\coderack.py", line 355, in run
    method()
  File "C:\Users\Owner\Dropbox\CS\AI\FARG\co.py.cat\copycat\codeletMethods.py", line 317, in replacement_finder
    0: slipnet.sameness,
AttributeError: 'module' object has no attribute 'sameness'

Also Scott Boland's site is down. Could you make a copy of his code available?

**Comment by jalanb** [comment]
I have only tested this code under Python 2, It was (probably) originally written under Python 2.5, but I have run under Python 2.7 as well.

I would not expect it to run directly under Python 3 (e.g. your error on line 49 of copycat.py is obviously because of Python3 expecting a print function rather than a print statement)

The missing attribute problem should be fixed by commit aeb8cda

I no longer have a copy of Scott Boland's code available to me.

**Comment by holdenlee** [comment]
This fixed it. Thanks for the quick response!
